<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TypedLayout.Core/TypedLayout.Core.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Syntax.fs" />
    <Compile Include="Parser.fs" />
    <Compile Include="Compiler.fs" />
  </ItemGroup>
</Project>
